services:
  postgres:
    image: postgres:17
    container_name: secretsalty_db
    environment:
      POSTGRES_DB: secretsalty_db
      POSTGRES_USER: secretsalty
      POSTGRES_PASSWORD: totally-secure-password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
